### ISSUE TITLE
GitHub Action does not properly handle version number passed as argument

### ISSUE THREAD

**Issue by rodrigc** [syntaqx/setup-kustomize#1]
@syntaqx This GitHub Action looks pretty cool, and I would like to use it.

This use-case:

```
steps:
  - uses: syntaqx/setup-kustomize@v1
    with:
      kustomize-version: 5.0.1
  - run: kustomize version
  ```
  
  Doesn't quite work though.
  
  This line here:
  
  ```
  curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash ${{ inputs.kustomize-version }}
```

will expand to:

```
curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash 5.0.2
```

That will try to run a command `5.0.2` which does not exist.

Maybe you want to do something like:

```
curl -O https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh
bash ./install_kustomize.sh ${{inputs.kustomize-version}}
```
